---
- name: Install deps pkg.
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - curl

# - name: Add Apt Repository.
#   raw: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

- name: Install docker.
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - docker
  notify: 
    - restart docker
